name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # eller den version av Node.js du använder

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run tests and collect coverage data
      - name: Run tests
        run: |
          npm test -- --coverage --watchAll=false

      # Upload coverage data to Codecov (valfritt, beroende på ditt verktyg)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov-report/index.js # Ändra detta beroende på var din täckningsfil finns
          token: ${{ secrets.CODECOV_TOKEN }} # Om du använder Codecov, annars kan du använda något annat

  check-coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Check out the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Fetch coverage report (adjust path if needed)
      - name: Fetch coverage report
        run: |
          COVERAGE=$(cat ./coverage/coverage-summary.json | jq .total.lines.pct)
          echo "Test coverage is ${COVERAGE}%"
          if (( $(echo "$COVERAGE < 85" | bc -l) )); then
            echo "Test coverage is below 85%, cannot merge."
            exit 1
          fi
  deploy:
    runs-on: ubuntu-latest
    needs: check-coverage

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Setup pages
        uses: actions/configure-pages@v3
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./dist"
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v1
